BEGIN
-- Seed file: v1 Persona Library (6 personas)
-- Reference: Master Plan §3.2

-- confident_desktop: Average tech-savvy adult on a fast desktop. Baseline.
INSERT INTO personas (
    id,
    display_name,
    age_band,
    device_class,
    network_profile,
    typing_wpm,
    typing_error_rate,
    reading_wpm,
    comprehension_grade_level,
    hesitation_ms_per_decision,
    retry_tolerance,
    distraction_probability,
    assistive_tech,
    motor_profile,
    language_proficiency,
    payment_familiarity,
    abandons_on,
    description,
    is_system,
    created_by,
    updated_by
) VALUES (
    'confident_desktop',
    'Alex, 35, tech-savvy professional',
    'adult',
    'desktop',
    'fast',
    75,
    0.01,
    250,
    12,
    200,
    2,
    0.03,
    'none',
    'normal',
    'native',
    'high',
    ARRAY[]::TEXT[],
    'Baseline persona: fast, accurate, minimal friction. Used as the control for comparison.',
    TRUE,
    'system',
    'system'
);

-- average_mobile: Adult on iPhone, normal network, distracted.
INSERT INTO personas (
    id,
    display_name,
    age_band,
    device_class,
    network_profile,
    typing_wpm,
    typing_error_rate,
    reading_wpm,
    comprehension_grade_level,
    hesitation_ms_per_decision,
    retry_tolerance,
    distraction_probability,
    assistive_tech,
    motor_profile,
    language_proficiency,
    payment_familiarity,
    abandons_on,
    description,
    is_system,
    created_by,
    updated_by
) VALUES (
    'average_mobile',
    'Jordan, 28, casual mobile user',
    'adult',
    'mobile',
    'normal',
    55,
    0.03,
    200,
    10,
    500,
    2,
    0.15,
    'none',
    'normal',
    'native',
    'medium',
    ARRAY[]::TEXT[],
    'Typical mobile user: moderate speed, occasional typos, distracted by notifications.',
    TRUE,
    'system',
    'system'
);

-- elderly_first_time: Senior, low-end tablet, 400% zoom acceptable, slow typing, low payment familiarity, abandons on captcha.
INSERT INTO personas (
    id,
    display_name,
    age_band,
    device_class,
    network_profile,
    typing_wpm,
    typing_error_rate,
    reading_wpm,
    comprehension_grade_level,
    hesitation_ms_per_decision,
    retry_tolerance,
    distraction_probability,
    assistive_tech,
    motor_profile,
    language_proficiency,
    payment_familiarity,
    abandons_on,
    description,
    is_system,
    created_by,
    updated_by
) VALUES (
    'elderly_first_time',
    'Eleanor, 72, first-time online',
    'senior',
    'low_end_mobile',
    'slow_3g',
    25,
    0.08,
    150,
    6,
    2000,
    1,
    0.02,
    'zoom_400',
    'normal',
    'native',
    'low',
    ARRAY['captcha', 'phone_verification', 'complex_forms'],
    'Elderly first-time user: very slow typing, high error rate, requires zoom, low payment confidence, abandons on complex challenges.',
    TRUE,
    'system',
    'system'
);

-- low_literacy_slow: Adult, comprehension grade 4, slow reading, mobile, second language, high hesitation.
INSERT INTO personas (
    id,
    display_name,
    age_band,
    device_class,
    network_profile,
    typing_wpm,
    typing_error_rate,
    reading_wpm,
    comprehension_grade_level,
    hesitation_ms_per_decision,
    retry_tolerance,
    distraction_probability,
    assistive_tech,
    motor_profile,
    language_proficiency,
    payment_familiarity,
    abandons_on,
    description,
    is_system,
    created_by,
    updated_by
) VALUES (
    'low_literacy_slow',
    'Maria, 42, second language, low literacy',
    'adult',
    'mobile',
    'normal',
    40,
    0.05,
    120,
    4,
    3000,
    1,
    0.10,
    'none',
    'normal',
    'second_language',
    'low',
    ARRAY['long_instructions', 'legal_text', 'multi_step'],
    'Low literacy second-language user: slow reading, struggles with complex copy, high hesitation on decisions.',
    TRUE,
    'system',
    'system'
);

-- screen_reader_user: Adult, desktop, NVDA-style emulation via accessibility tree, keyboard-only.
INSERT INTO personas (
    id,
    display_name,
    age_band,
    device_class,
    network_profile,
    typing_wpm,
    typing_error_rate,
    reading_wpm,
    comprehension_grade_level,
    hesitation_ms_per_decision,
    retry_tolerance,
    distraction_probability,
    assistive_tech,
    motor_profile,
    language_proficiency,
    payment_familiarity,
    abandons_on,
    description,
    is_system,
    created_by,
    updated_by
) VALUES (
    'screen_reader_user',
    'Sam, 38, screen reader user',
    'adult',
    'desktop',
    'fast',
    60,
    0.02,
    180,
    12,
    800,
    3,
    0.05,
    'screen_reader',
    'normal',
    'native',
    'high',
    ARRAY[]::TEXT[],
    'Screen reader user: keyboard-only navigation, relies on accessibility tree, requires proper labels and focus order.',
    TRUE,
    'system',
    'system'
);

-- motor_impaired_tremor: Adult, mobile, tremor profile (drift on taps), needs large targets, slower interactions.
INSERT INTO personas (
    id,
    display_name,
    age_band,
    device_class,
    network_profile,
    typing_wpm,
    typing_error_rate,
    reading_wpm,
    comprehension_grade_level,
    hesitation_ms_per_decision,
    retry_tolerance,
    distraction_probability,
    assistive_tech,
    motor_profile,
    language_proficiency,
    payment_familiarity,
    abandons_on,
    description,
    is_system,
    created_by,
    updated_by
) VALUES (
    'motor_impaired_tremor',
    'Taylor, 45, motor impairment (tremor)',
    'adult',
    'mobile',
    'normal',
    35,
    0.06,
    180,
    10,
    1000,
    2,
    0.08,
    'none',
    'tremor',
    'native',
    'medium',
    ARRAY['small_targets', 'precise_taps'],
    'Motor-impaired user with tremor: difficulty with small targets, needs larger touch areas, slower deliberate interactions.',
    TRUE,
    'system',
    'system'
);
END;
