import {
  AgeBand, DeviceClass, NetworkProfileType, AssistiveTech,
  MotorProfile, LanguageProficiency, PaymentFamiliarity, type Persona
} from '@qa-platform/shared-types';

// v1 Persona Library — 6 seeded first-class personas
// Values calibrated per master plan §3.2

const now = new Date('2026-01-01T00:00:00Z');

export const V1_PERSONAS: Persona[] = [
  {
    id: 'confident_desktop',
    display_name: 'Alex, 34 – Tech-savvy desktop user',
    age_band: AgeBand.ADULT,
    device_class: DeviceClass.DESKTOP,
    network_profile: NetworkProfileType.FAST,
    typing_wpm: 75,
    typing_error_rate: 0.01,
    reading_wpm: 250,
    comprehension_grade_level: 12,
    hesitation_ms_per_decision: 300,
    retry_tolerance: 5,
    distraction_probability: 0.02,
    assistive_tech: AssistiveTech.NONE,
    motor_profile: MotorProfile.NORMAL,
    language_proficiency: LanguageProficiency.NATIVE,
    payment_familiarity: PaymentFamiliarity.HIGH,
    abandons_on: [],
    created_date: now,
    updated_date: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'average_mobile',
    display_name: 'Maria, 28 – iPhone user, easily distracted',
    age_band: AgeBand.ADULT,
    device_class: DeviceClass.MOBILE,
    network_profile: NetworkProfileType.NORMAL,
    typing_wpm: 45,
    typing_error_rate: 0.04,
    reading_wpm: 200,
    comprehension_grade_level: 10,
    hesitation_ms_per_decision: 600,
    retry_tolerance: 3,
    distraction_probability: 0.15,
    assistive_tech: AssistiveTech.NONE,
    motor_profile: MotorProfile.NORMAL,
    language_proficiency: LanguageProficiency.NATIVE,
    payment_familiarity: PaymentFamiliarity.HIGH,
    abandons_on: ['long_form', 'document_upload'],
    created_date: now,
    updated_date: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'elderly_first_time',
    display_name: 'Eleanor, 72 – First-time online, low-end tablet',
    age_band: AgeBand.SENIOR,
    device_class: DeviceClass.TABLET,
    network_profile: NetworkProfileType.SLOW_3G,
    typing_wpm: 25,
    typing_error_rate: 0.08,
    reading_wpm: 120,
    comprehension_grade_level: 5,
    hesitation_ms_per_decision: 2000,
    retry_tolerance: 2,
    distraction_probability: 0.05,
    assistive_tech: AssistiveTech.ZOOM_400,
    motor_profile: MotorProfile.NORMAL,
    language_proficiency: LanguageProficiency.NATIVE,
    payment_familiarity: PaymentFamiliarity.LOW,
    abandons_on: ['captcha', 'phone_verification', 'complex_forms', 'multi_step_payment'],
    created_date: now,
    updated_date: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'low_literacy_slow',
    display_name: 'Carlos, 41 – Grade-4 comprehension, second language',
    age_band: AgeBand.ADULT,
    device_class: DeviceClass.MOBILE,
    network_profile: NetworkProfileType.SLOW_3G,
    typing_wpm: 30,
    typing_error_rate: 0.06,
    reading_wpm: 130,
    comprehension_grade_level: 4,
    hesitation_ms_per_decision: 1800,
    retry_tolerance: 2,
    distraction_probability: 0.10,
    assistive_tech: AssistiveTech.NONE,
    motor_profile: MotorProfile.NORMAL,
    language_proficiency: LanguageProficiency.SECOND_LANGUAGE,
    payment_familiarity: PaymentFamiliarity.LOW,
    abandons_on: ['legal_text_wall', 'complex_forms', 'error_message_unclear'],
    created_date: now,
    updated_date: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'screen_reader_user',
    display_name: 'Jordan, 38 – Desktop, keyboard-only / screen reader',
    age_band: AgeBand.ADULT,
    device_class: DeviceClass.DESKTOP,
    network_profile: NetworkProfileType.NORMAL,
    typing_wpm: 55,
    typing_error_rate: 0.02,
    reading_wpm: 180,
    comprehension_grade_level: 12,
    hesitation_ms_per_decision: 800,
    retry_tolerance: 3,
    distraction_probability: 0.02,
    assistive_tech: AssistiveTech.SCREEN_READER,
    motor_profile: MotorProfile.NORMAL,
    language_proficiency: LanguageProficiency.NATIVE,
    payment_familiarity: PaymentFamiliarity.HIGH,
    abandons_on: ['image_only_captcha', 'missing_aria_labels'],
    created_date: now,
    updated_date: now,
    created_by: 'system',
    updated_by: 'system',
  },
  {
    id: 'motor_impaired_tremor',
    display_name: 'Sam, 52 – Mobile, hand tremor, needs large targets',
    age_band: AgeBand.ADULT,
    device_class: DeviceClass.MOBILE,
    network_profile: NetworkProfileType.NORMAL,
    typing_wpm: 20,
    typing_error_rate: 0.07,
    reading_wpm: 180,
    comprehension_grade_level: 10,
    hesitation_ms_per_decision: 1200,
    retry_tolerance: 4,
    distraction_probability: 0.03,
    assistive_tech: AssistiveTech.NONE,
    motor_profile: MotorProfile.TREMOR,
    language_proficiency: LanguageProficiency.NATIVE,
    payment_familiarity: PaymentFamiliarity.HIGH,
    abandons_on: ['small_tap_targets', 'drag_required'],
    created_date: now,
    updated_date: now,
    created_by: 'system',
    updated_by: 'system',
  },
];

export function getPersonaById(id: string): Persona | undefined {
  return V1_PERSONAS.find(p => p.id === id);
}

export function getPersonasByDeviceClass(deviceClass: DeviceClass): Persona[] {
  return V1_PERSONAS.filter(p => p.device_class === deviceClass);
}

export function getPersonasByAssistiveTech(tech: AssistiveTech): Persona[] {
  return V1_PERSONAS.filter(p => p.assistive_tech === tech);
}
